name: 'icair-multi-pa-nsa'

# This is the master docker-compose file for the ICAIR multi-PA NSA node.
# It uses the compose include feature to include all the individual component files.
# 
# Usage:
#   To start all services:       docker-compose up -d
#   To start specific services:  docker-compose up -d ag-ra pa-ar400
#   To view logs:               docker-compose logs -f
#   To stop all services:       docker-compose down
#
# Components:
#   - ag-ra: Aggregator/Requester Agent with DDS, PCE, Safnari, NSI-Requester
#   - pa-ar400: Provider Agent for AR400 switch (Arista EOS4)
#   - pa-z9432f: Provider Agent for Z9432F switch (Dell OS10)
#   - pa-z9664f: Provider Agent for Z9664F switch (Dell OS10)

include:
  - path: ./ag-ra/docker-compose.yaml
    project_directory: ./ag-ra
  - path: ./pa-ar400/docker-compose.yaml  
    project_directory: ./pa-ar400
  - path: ./pa-z9432f/docker-compose.yaml
    project_directory: ./pa-z9432f
  - path: ./pa-z9664f/docker-compose.yaml
    project_directory: ./pa-z9664f

# Port mapping summary:
# AG-RA services:
#   - DDS: 8401
#   - PCE: 8090  
#   - Safnari: 9080
#   - NSI-Requester: 9000
# PA-AR400 services:
#   - SuPA: 4321
#   - PolyNSI: 8443
# PA-Z9432F services:
#   - SuPA: 4322
#   - PolyNSI: 8444
# PA-Z9664F services:
#   - SuPA: 4323
#   - PolyNSI: 8445 