stps:
  # - stp_id: my_stp1                       # Required, str, Uniq ID of the STP.
  #   port_id: Ethernet1                    # Required, str, ID of the corresponding port.
  #   vlans: "1728-1799"                    # Required, str, VLANs part of this STP.
  #   description: "my test stp 1 with vlan range 1728-1799."         # Optional, str, STP description.
  #   is_alias_in: connected_stp_out                # Optional, str, Inbound STP ID from connected topology.
  #   is_alias_out: connected_stp_in               # Optional, str, Outbound STP ID to connected topology.
  #   bandwidth: 1000                       # Required, int, Available bandwidth for this STP in Mbps.
  #   enabled: True                         # Optional, bool, STP status.

  - stp_id: nycu-sw
    port_id: Et1
    vlans: "1700-1799"
    description: "VLAN range 1700-1799, to NYCU STP icair-arista."
    is_alias_in: "urn:ogf:network:nycu.edu.tw:2025:topology:icair-arista:out"
    is_alias_out: "urn:ogf:network:nycu.edu.tw:2025:topology:icair-arista:in"
    enabled: True

  - stp_id: nycu-test
    port_id: Et2
    vlans: "1700-1799"
    description: "VLAN range 1700-1799, to NYCU STP icair-test."
    is_alias_in: "urn:ogf:network:nycu.edu.tw:2025:topology:icair-test:out"
    is_alias_out: "urn:ogf:network:nycu.edu.tw:2025:topology:icair-test:in"
    enabled: True

