stps:
  # Bidirectional STP (standard case, with ":in" and ":out")
  - stp_id: my_stp1
    port_id: ethernet1
    vlans: "1700-1728"
    description: "Test STP to TWAREN StarLight"
    remote_stp:
      prefix_urn: "urn:ogf:network:twaren.nchc.org:2014:topology"
      id: "starlight"
    bandwidth: 1000
    enabled: True

  # STP with different in/out connections
  - stp_id: my_stp2
    port_id: ethernet2
    vlans: "1700-1799"
    description: "STP to iCAIR OpenNSA mren8700 ar100"
    remote_stp_in:
      prefix_urn: "urn:ogf:network:icair.org:2013:mren8700"
      id: "ar100-out"
    remote_stp_out:
      prefix_urn: "urn:ogf:network:icair.org:2013:mren8700"
      id: "ar100-in"
    bandwidth: 1000
    enabled: True
