stps:
  # - stp_id: my_stp1                       # Required, str, Uniq ID of the STP.
  #   port_id: Ethernet1                    # Required, str, ID of the corresponding port.
  #   vlans: "1728-1799"                    # Required, str, VLANs part of this STP.
  #   description: "my test stp 1 with vlan range 1728-1799."         # Optional, str, STP description.
  #   is_alias_in: connected_stp_out                # Optional, str, Inbound STP ID from connected topology.
  #   is_alias_out: connected_stp_in               # Optional, str, Outbound STP ID to connected topology.
  #   bandwidth: 1000                       # Required, int, Available bandwidth for this STP in Mbps.
  #   enabled: True                         # Optional, bool, STP status.

  - stp_id: icair-arista
    port_id: Et1
    vlans: "1700-1799"
    description: "VLAN range 1700-1799, to iCAIR STP nycu-sw."
    # is_alias_in: "urn:ogf:network:icairtest.org:2025:topology:nycu-sw:out"
    # is_alias_out: "urn:ogf:network:icairtest.org:2025:topology:nycu-sw:in"
    enabled: True

  - stp_id: icair-test
    port_id: Et2
    vlans: "1700-1799"
    description: "VLAN range 1700-1799, to iCAIR STP nycu-test."
    # is_alias_in: "urn:ogf:network:icairtest.org:2025:topology:nycu-test:out"
    # is_alias_out: "urn:ogf:network:icairtest.org:2025:topology:nycu-test:in"
    enabled: True

